RailwayOrientedProgramming/src/Result/Extensions/Bind.cs
RailwayOrientedProgramming/src/Result/Extensions/ParallelAsync.cs
RailwayOrientedProgramming/tests/Results/Extensions/ParallelTests.cs

Add ability to run tasks in parallel.

Parallel async

---

Examples/SampleWebApplication/src/Aggregate/User.cs
Examples/Xunit/AsyncUsageExamples.cs
README.md
RailwayOrientedProgramming/src/Result/Extensions/IfErrorTap.cs
RailwayOrientedProgramming/src/Result/Extensions/IfOkTap.cs

IfOkTap to call functions that return void.

IfOkTap to call functions that return void.

---

Directory.Build.props

Add PackageProjectUrl

---

.github/workflows/build.yml
Examples/SampleWebApplication/Requests/Register.http
RailwayOrientedProgramming/src/Errors/Error.cs
global.json

Add Target to error object.

---

DomainDrivenDesign/src/Entity.cs

Add nullable to Entity operator.

Add nullable to Entity operator.

---

RailwayOrientedProgramming/src/Errors/Error.cs
RailwayOrientedProgramming/src/Errors/Types/ConflictError.cs
RailwayOrientedProgramming/src/Errors/Types/ForbiddenError.cs
RailwayOrientedProgramming/src/Errors/Types/NotFoundError.cs
RailwayOrientedProgramming/src/Errors/Types/UnauthorizedError.cs
RailwayOrientedProgramming/src/Errors/Types/UnexpectedError.cs
RailwayOrientedProgramming/tests/ErrorTests.cs

Add short cut to add target to error.

Add short cut to add target to error.

---

RailwayOrientedProgramming/src/Result/Extensions/Tee.cs
RailwayOrientedProgramming/tests/Results/Extensions/TeeTests.cs

Add Tee extension methods for ValueTask

Add Tee extension methods for Result ValueTask

---

RailwayOrientedProgramming/src/Result/Extensions/Finally.cs
RailwayOrientedProgramming/tests/Results/Extensions/FinallyTests.cs

Add FinallyAsync for value task

Add FinallyAsync for value task

---

RailwayOrientedProgramming/src/Maybe/Extensions/ToResult.cs
RailwayOrientedProgramming/src/Result/Result.cs
RailwayOrientedProgramming/tests/Results/Extensions/EnsureTests.Task.Left.cs
RailwayOrientedProgramming/tests/Results/Extensions/EnsureTests.cs
RailwayOrientedProgramming/tests/Results/ResultTests.cs

Set Result via callback
```
Result.Success(() => "Hello");
Result.Failure<string>(() => Error.Validation("Bad first name"));
```

Set Result via callback

---

Asp/src/ActionResultExtensions.cs
Asp/src/PartialObjectResult.cs
Asp/tests/ActionResultTests.cs
Asp/tests/Asp.Tests.csproj
Asp/tests/HttpPartialObjectResultTest.cs
Asp/tests/TestHttpResponseStreamWriterFactory.cs
Directory.Packages.props
DomainDrivenDesign/src/ValueObject.cs
Examples/SampleWebApplication/src/Controllers/WeatherForecastController.cs
FunctionalDDD.sln
RailwayOrientedProgramming/src/Result/Extensions/HttpResponseMessageJsonExtensions.cs
RailwayOrientedProgramming/tests/Results/Extensions/BindTests.ValueTask.cs
RailwayOrientedProgramming/tests/Results/Extensions/BindsTests.ValueTask.Left.cs
RailwayOrientedProgramming/tests/Results/Extensions/BindsTests.ValueTask.Right.cs
RailwayOrientedProgramming/tests/Results/Extensions/FinallyTests.cs
RailwayOrientedProgramming/tests/Results/Extensions/HttpResponseMessageJsonExtensionsTests.cs

Support for partial content.
```
.ToPartialOrOkActionResult(this, 0, 3, 5);
```
Sample response header.
```
content-range: items 0-3/5 
content-type: application/json; charset=utf-8 
date: Mon,31 Jul 2023 19:41:49 GMT 
server: Kestrel 
```

Support for partial content.

---

Asp/src/ActionResultExtensions.cs
FluentValidation/src/FluentValidationExtension.cs
RailwayOrientedProgramming/README.md
RailwayOrientedProgramming/src/Result/Result{TValue}.cs
docs/docfx_project/articles/examples.md

Add ActionResult documentation.

Add ActionResult documentation.

---

Asp/src/ActionResultExtensions.cs
Asp/src/ActionResultExtensionsAsync.cs
Asp/src/Asp.csproj
Asp/src/ContentRangeAndData.cs
Asp/tests/ActionResultTaskTests.cs
Asp/tests/ActionResultTests.cs
Asp/tests/ActionResultValueTaskTests.cs
CommonValueObjects/src/CommonValueObjects.csproj
DomainDrivenDesign/src/DomainDrivenDesign.csproj
Examples/SampleWebApplication/src/Controllers/WeatherForecastController.cs
RailwayOrientedProgramming/src/RailwayOrientedProgramming.csproj
docs/docfx_project/articles/intro.md

Callback support for async Partial content.

Callback support for async Partial content.

---

Asp/src/ActionResultExtensions.cs
Asp/src/ActionResultExtensionsAsync.cs
Asp/src/Asp.csproj
Asp/src/PartialObjectResult.cs
Asp/tests/ActionResultTaskTests.cs
Asp/tests/ActionResultTests.cs
Asp/tests/ActionResultValueTaskTests.cs
Asp/tests/HttpPartialObjectResultTest.cs
Examples/SampleWebApplication/src/Controllers/AuthenticationController.cs
Examples/SampleWebApplication/src/Controllers/WeatherForecastController.cs

Rename 
from -> rangeStart, 
to -> rangeEnd
per spec https://www.rfc-editor.org/rfc/rfc9110#field.content-range

Rename from to rangeStart

---

CommonValueObjects/generator/CommonValueObjectGenerator.csproj
FluentValidation/src/FluentValidation.csproj

Add description to nuget packages missing a description.

Add description to nuget packages missing a description.

---

Benchmark/Benchmark.csproj

Don't pack benchmark assembly

---

.github/workflows/build.yml
Asp/tests/HttpPartialObjectResultTest.cs
Directory.Build.props
Directory.Packages.props
DomainDrivenDesign/src/ValueObject.cs
Examples/SampleWebApplication/src/Controllers/AuthenticationController.cs
Examples/SampleWebApplication/src/Controllers/WeatherForecastController.cs
FunctionalDDD.sln
RailwayOrientedProgramming/src/Result/Extensions/CombineError.cs
global.json
version.json

Upgrade to .NET 8

---

Asp/src/Asp.csproj
CommonValueObjects/src/CommonValueObjects.csproj
Directory.Build.props
DomainDrivenDesign/src/DomainDrivenDesign.csproj
FluentValidation/src/FluentValidation.csproj
FluentValidation/src/FluentValidationExtension.cs
FluentValidation/tests/FluentTests.cs
FluentValidation/tests/ValueObject/ZipCode.cs
RailwayOrientedProgramming/src/RailwayOrientedProgramming.csproj
global.json

Support for null model to fluent validation.

Support for null model to fluent validation.

---

RailwayOrientedProgramming/src/Result/Result.cs
RailwayOrientedProgramming/tests/Results/ResultTests.cs

Add short cut for Unit Result.

Add short cut for Unit Result.

---

RailwayOrientedProgramming/src/RailwayOrientedProgramming.csproj
RailwayOrientedProgramming/src/Result/IResult.cs
RailwayOrientedProgramming/src/Result/IResult{TValue}.cs
RailwayOrientedProgramming/src/Result/Result{TValue}.cs

Add interface IResult

---

CommonValueObjects/src/EmailAddress.cs
CommonValueObjects/tests/EmailAddressTests.cs
Directory.Packages.props
Examples/Xunit/Example.Tests.csproj

Update nuget packages

---

DomainDrivenDesign/src/Aggregate.cs
DomainDrivenDesign/src/IAggregate.cs
DomainDrivenDesign/src/IDomainEvent.cs
RailwayOrientedProgramming/src/Result/Extensions/Combine.cs
RailwayOrientedProgramming/tests/Results/Extensions/CombineTests.cs

Add domain event.

---

RailwayOrientedProgramming/src/Result/Extensions/Bind.cs
RailwayOrientedProgramming/tests/Results/Extensions/BindTests.Task.cs
RailwayOrientedProgramming/tests/Results/Extensions/ParallelTests.cs

Task<Result<TResult>> BindAsync<T1, T2, TResult>(this Result<(T1, T2)> result, Func<T1, T2, Task<Result<TResult>>> func)
Task<Result<TResult>> BindAsync<T1, T2, TResult>(this Task<Result<(T1, T2)>> resultTask, Func<T1, T2, Task<Result<TResult>>> func)

Additional BindAsync methods

---

RailwayOrientedProgramming/src/Result/Extensions/Bind.cs
RailwayOrientedProgramming/src/Result/Extensions/BindTs.g.tt
RailwayOrientedProgramming/src/Result/Extensions/CombineError.cs
RailwayOrientedProgramming/src/Result/Extensions/CombineTs.g.tt
RailwayOrientedProgramming/src/Result/Internal/TaskExtensions.cs
RailwayOrientedProgramming/tests/Results/Extensions/CombineTests.cs

T4 generation of BindAsync variations.

T4 generation of BindAsync variations.

---

RailwayOrientedProgramming/tests/Results/Extensions/HttpResponseMessageJsonExtensionsTests.cs

Add test case for Maybe<T> for http get request

Add test case for Maybe<T> for http get request

---

Directory.Packages.props
Examples/Xunit/AsyncUsageExamples.cs
Examples/Xunit/Example.Tests.csproj
Examples/Xunit/TraceFixture.cs
README.md
RailwayOrientedProgramming/src/RailwayOrientedProgramming.csproj
RailwayOrientedProgramming/src/Result/Extensions/Bind.cs
RailwayOrientedProgramming/src/Result/Extensions/Compensate.cs
RailwayOrientedProgramming/src/Result/Extensions/Ensure.Task.Left.cs
RailwayOrientedProgramming/src/Result/Extensions/Ensure.cs
RailwayOrientedProgramming/src/Result/Extensions/Finally.cs
RailwayOrientedProgramming/src/Result/Extensions/NullableExtensions.cs
RailwayOrientedProgramming/src/Result/Extensions/Tap.cs
RailwayOrientedProgramming/src/Result/Extensions/TapError.cs
RailwayOrientedProgramming/src/Result/Result{TValue}.cs
RailwayOrientedProgramming/src/Trace.cs
RailwayOrientedProgramming/src/TracerProviderBuilderExtensions.cs

Add Tracing to some functions. If it is useful, it can be expanded to all functions.
Success
Failed

Add OTEL Tracing

---

README.md
RailwayOrientedProgramming/README.md
RailwayOrientedProgramming/src/RailwayOrientedProgramming.csproj
RailwayOrientedProgramming/src/Result/Extensions/AwaitTs.g.tt
RailwayOrientedProgramming/src/Result/Extensions/BindTs.g.tt
RailwayOrientedProgramming/tests/Results/Extensions/ParallelTests.cs

Add method AwaitAsync for better composition.
```csharp
var r = await _sender.Send(new StudentInformationQuery(studentId)
.ParallelAsync(_sender.Send(new StudentGradeQuery(studentId))
.ParallelAsync(_sender.Send(new LibraryCheckedOutBooksQuery(studentId))
.AwaitAsync()
.BindAsync((studentInformation, studentGrades, checkoutBooks)
=> PrepareReport(studentInformation, studentGrades, checkoutBooks));
```

Add method AwaitAsync

---

RailwayOrientedProgramming/src/RailwayOrientedProgramming.csproj
RailwayOrientedProgramming/src/Result/Extensions/Map.cs
RailwayOrientedProgramming/src/Result/Extensions/MapTs.g.tt
RailwayOrientedProgramming/src/Result/Extensions/Tap.cs
RailwayOrientedProgramming/src/Result/Extensions/TapTs.g.tt
RailwayOrientedProgramming/tests/Results/Extensions/ParallelTests.cs

Additional Tap and Map functions

Additional Tap and Map functions

---

Asp/src/ActionResultExtensions.cs
Asp/tests/ActionResultTaskTests.cs
Benchmark/BenchmarkROP.cs
Examples/SampleWebApplication/src/Controllers/WeatherForecastController.cs
Examples/Xunit/AsyncUsageExamples.cs
FluentValidation/src/FluentValidationExtension.cs
RailwayOrientedProgramming/src/Errors/Error.cs
RailwayOrientedProgramming/src/Errors/Types/BadRequestError.cs
RailwayOrientedProgramming/src/Errors/Types/ConflictError.cs
RailwayOrientedProgramming/src/Errors/Types/ForbiddenError.cs
RailwayOrientedProgramming/src/Errors/Types/NotFoundError.cs
RailwayOrientedProgramming/src/Errors/Types/UnauthorizedError.cs
RailwayOrientedProgramming/src/Errors/Types/UnexpectedError.cs
RailwayOrientedProgramming/src/Errors/Types/ValidationError.cs
RailwayOrientedProgramming/src/Result/Extensions/CombineError.cs
RailwayOrientedProgramming/tests/ErrorTests.cs
RailwayOrientedProgramming/tests/Maybes/OptionalTests.cs
RailwayOrientedProgramming/tests/Results/Extensions/ReadResultFromJsonTests.cs
RailwayOrientedProgramming/tests/Results/Extensions/ReadResultMaybeFromJsonTests.cs

ValidationError Use arrays.

---

RailwayOrientedProgramming/src/Result/Extensions/TapTs.g.tt
RailwayOrientedProgramming/tests/RailwayOrientedProgramming.Tests.csproj
RailwayOrientedProgramming/tests/Results/Extensions/BindTests.cs
RailwayOrientedProgramming/tests/Results/Extensions/BindTests.g.tt
RailwayOrientedProgramming/tests/Results/Extensions/ParallelTests.g.tt
RailwayOrientedProgramming/tests/Results/Extensions/TapTests.cs
RailwayOrientedProgramming/tests/Results/Extensions/TapTests.g.tt

TapAsync methods for Tasks and ValueTasks

TapAsync methods for Tasks and ValueTasks

---

global.json

Update .net 8 sdk to 8.0.303

---

CommonValueObjects/tests/RequiredGuidTests.cs
CommonValueObjects/tests/RequiredStringTests.cs

Add test case for Contains.

---

Examples/SampleMinimalApi/SampleMinimalApi.csproj
Examples/SampleUserLibrary/SampleUserLibrary.csproj
Examples/SampleWebApplication/src/SampleWebApplication.csproj

Remove sample library from NuGet packing

Remove sample library from NuGet packing

---

CommonValueObjects/generator/RequiredPartialClassGenerator.cs
CommonValueObjects/src/EmailAddress.cs
CommonValueObjects/src/ParsableJsonConverter.cs
CommonValueObjects/tests/EmailAddressTests.cs
CommonValueObjects/tests/RequiredGuidTests.cs
CommonValueObjects/tests/RequiredStringTests.cs
DomainDrivenDesign/src/Aggregate.cs
DomainDrivenDesign/src/ScalarValueObject.cs
DomainDrivenDesign/src/ValueObject.cs
Examples/SampleMinimalApi/Program.cs
Examples/SampleUserLibrary/Model/RegisterUserResponse.cs

Can we get RequiredString, RequiredGuid and RequiredEmail to behave like primitive type during JSON Convert?

ConvertToJson Unit test.

---

Benchmark/Benchmark.BenchmarkROP.8.0.403.md
Benchmark/Benchmark.csproj
Benchmark/BenchmarkROP.cs

Check in benchmark result

---

CommonValueObjects/generator/RequiredPartialClassGenerator.cs
CommonValueObjects/src/CommonValueObjectTrace.cs
CommonValueObjects/src/CommonValueObjectTraceProviderBuilderExtensions.cs
CommonValueObjects/src/EmailAddress.cs
Directory.Packages.props
Examples/SampleMinimalApi/Program.cs
Examples/SampleMinimalApi/SampleMinimalApi.csproj
Examples/SampleUserLibrary/SampleUserLibrary.csproj
Examples/Xunit/TraceFixture.cs
README.md
RailwayOrientedProgramming/src/Result/Extensions/Bind.cs
RailwayOrientedProgramming/src/Result/Extensions/BindTs.g.tt
RailwayOrientedProgramming/src/Result/Extensions/Combine.cs
RailwayOrientedProgramming/src/Result/Extensions/CombineTs.g.tt
RailwayOrientedProgramming/src/Result/Extensions/Compensate.cs
RailwayOrientedProgramming/src/Result/Extensions/Ensure.cs
RailwayOrientedProgramming/src/Result/Extensions/Finally.cs
RailwayOrientedProgramming/src/Result/Extensions/Map.cs
RailwayOrientedProgramming/src/Result/Extensions/NullableExtensions.cs
RailwayOrientedProgramming/src/Result/Extensions/Tap.cs
RailwayOrientedProgramming/src/Result/Extensions/TapError.cs
RailwayOrientedProgramming/src/Result/Extensions/TapTs.g.tt
RailwayOrientedProgramming/src/RopTrace.cs
RailwayOrientedProgramming/src/RopTracerProviderBuilderExtensions.cs
RailwayOrientedProgramming/src/TracerProviderBuilderExtensions.cs

AddFunctionalDddCommonValueObjectInstrumentation to trace common value objects.
eg. 
Firstname valid
Lastname invalid
Email invalid

AddFunctionalDddCommonValueObjectInstrumentation

---

Asp/README.md
Asp/src/ActionResultExtensions.cs
Asp/src/HttpResultExtensions.cs
Examples/SampleMinimalApi/Program.cs
Examples/SampleWebApplication/src/Controllers/UsersController.cs
Examples/SampleWebApplication/src/Controllers/WeatherForecastController.cs

ToErrorActionResult to ToActionResult
ToErrorResult to ToHttpResult

Rename ToErrorActionResult to ToActionResult

---

.editorconfig
Asp/src/HttpResultExtensions.cs
Asp/tests/ResultsTests.cs
Examples/SampleMinimalApi/API/ToDodoRoutes.cs
Examples/SampleMinimalApi/API/UserRoutes.cs
Examples/SampleMinimalApi/Program.cs
Examples/SampleMinimalApi/SampleMinimalApi.http
Examples/SampleUserLibrary/Aggregate/User.cs
FluentValidation/src/FluentValidationExtension.cs
FluentValidation/tests/Aggregate/User.cs
FluentValidation/tests/FluentTests.cs

Sample: Add complex password validation.
Add `required` to properties.

Sample: Add complex password validation

---

Asp/src/ActionResultExtensions.cs
Asp/src/ActionResultExtensionsAsync.cs
Asp/tests/HttpResultValueTaskTests.cs
Asp/tests/HttpResultsTests.cs
Examples/SampleWebApplication/src/Controllers/UsersController.cs

Removed ToErrorActionResult API

Removed ToErrorActionResult API

---

RailwayOrientedProgramming/src/Errors/Error.cs
RailwayOrientedProgramming/src/Errors/Types/ValidationError.cs
RailwayOrientedProgramming/tests/ErrorTests.cs
build.cmd

Validation Default detail to field detail when detail is null in a specific case.

Validation Default detail to field detail in a specific case.

---

global.json
version.json

Announcing the release of version 2 of the library, now built on .NET 8! This update includes significant breaking changes from version 1, introducing new features and improvements.

Version 2.0

---

.github/workflows/build.yml
.github/workflows/documentation.yml
CommonValueObjects/src/ParsableJsonConverter.cs
version.json

Add documentation to build

---

RailwayOrientedProgramming/src/Errors/Error.cs
RailwayOrientedProgramming/src/Errors/Types/ValidationError.cs
RailwayOrientedProgramming/tests/ErrorTests.cs
version.json

Add ToString overload for error class.
Update version

Add ToString overload for error class.
